import Head from "next/head";
import Patients from "../components/pages/patients";
import MainLayout from "../layouts/layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col">
        <div className="container mx-auto">
          <p className="text-3xl font-bold">HOME PAGE</p>
        </div>
      </main>
    </>
  );
}

Home.getLayout = function getLayout(page: React.ReactElement) {
  return <MainLayout>{page}</MainLayout>;
};
